//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork10.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID { get; set; }
        public string SecondName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime EditDate { get; set; }
        public Nullable<int> ResponsibleWorker { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
